### ISSUE TITLE
data_adhesin_64_1nm_1um.h5 corrupted ?

### ISSUE THREAD

**Issue by RadouaneBjm** [mdw771/adorym#4]
Hello,

Thank you very much for sharing your codes with the Github community.
Actually,I tried to run _test_multislice_ptycho_64.py script but it seems that "**data_adhesin_64_1nm_1um.h5**" file is corrupted (I downloaded it twice to make sure the file was downloaded properly)
if it'is the case,could you please re-upload it ?
below the error message displayed after reading the file separately
**Unable to open file (truncated file: eof = 10244227072, sblock->base_addr = 0, stored_eof = 10969346456)**

Thank you.

**Comment by mdw771** [comment]
Hi,

Please try this HDF5 instead: https://drive.google.com/file/d/1sKOiiyU__UTWuN6EIzooaOw9Xbv9ZSmu/view?usp=sharing

The Box account that is currently hosting the data files is linked to my previous organization's account and is no longer accessible to me. I might need to move the data to a new host.

**Comment by RadouaneBjm** [comment]
Hi,
Thanks a lot, now I can read the file properly.
